name: Manual build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'jyothika'

      age:
        description: 'Age'
        type: number
        required: true
        
  


jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: name
        run:  echo "${{ inputs.name }}"

      - name: age
        run:  echo "${{ inputs.age }}"
